apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app.kubernetes.io/part-of: iu-exchange
    app.kubernetes.io/name: backend
  ports:
    - port: 1234
      targetPort: 8516
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app.kubernetes.io/part-of: iu-exchange
        app.kubernetes.io/name: backend
    spec:
      containers:
      - name: backend
        image: iu-exchange:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "run.py", "-p", "8516", "prod.toml"]
        envFrom:
          - configMapRef:
              name: database-config
        ports:
        - containerPort: 8516
