apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app.kubernetes.io/part-of: iu-exchange
    app.kubernetes.io/name: database
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pv-claim
  labels:
    app.kubernetes.io/part-of: iu-exchange
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: database
  selector:
    matchLabels:
      app.kubernetes.io/name: database
  template:
    metadata:
      name: database
      labels:
        app.kubernetes.io/part-of: iu-exchange
        app.kubernetes.io/name: database
    spec:
      containers:
      - name: database
        image: postgres:12.1-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: database-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: database-persistent-storage
          persistentVolumeClaim:
            claimName: database-pv-claim
